/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Builder.io Dark Mode Colors (dark mode only)
        'builder': {
          'dark': {
            'primary': '#0a0a0a',
            'secondary': '#111111',
            'tertiary': '#1a1a1a',
          },
          'card': '#ffffff',
          'cardHover': '#f8f9fa',
          'foreground': {
            'primary': '#ffffff',
            'secondary': '#e5e5e5',
            'tertiary': '#b3b3b3',
            'onCard': '#0a0a0a',
          },
          'accent': {
            'primary': '#3b82f6',
            'primaryHover': '#2563eb',
            'primaryActive': '#1d4ed8',
            'secondary': '#6366f1',
          },
          'border': {
            'default': '#2a2a2a',
            'light': '#1a1a1a',
            'card': '#e5e5e5',
            'focus': '#3b82f6',
          },
          'success': '#10b981',
          'warning': '#f59e0b',
          'error': '#ef4444',
        },
      },
      fontFamily: {
        'sans': ['Poppins', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', '"Helvetica Neue"', 'Arial', 'sans-serif'],
        'heading': ['Poppins', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', '"Helvetica Neue"', 'Arial', 'sans-serif'],
        'mono': ['"SF Mono"', 'Monaco', '"Cascadia Code"', '"Roboto Mono"', 'Consolas', '"Courier New"', 'monospace'],
      },
      fontSize: {
        'xs': '12px',
        'sm': '14px',
        'base': '16px',
        'md': '18px',
        'lg': '20px',
        'xl': '24px',
        '2xl': '30px',
        '3xl': '36px',
        '4xl': '48px',
        '5xl': '64px',
        'h1': ['48px', { lineHeight: '1.2', fontWeight: '700', letterSpacing: '-0.02em' }],
        'h2': ['36px', { lineHeight: '1.2', fontWeight: '700', letterSpacing: '-0.02em' }],
        'h3': ['30px', { lineHeight: '1.3', fontWeight: '600', letterSpacing: '-0.01em' }],
        'h4': ['24px', { lineHeight: '1.4', fontWeight: '600', letterSpacing: '0' }],
        'h5': ['20px', { lineHeight: '1.4', fontWeight: '600', letterSpacing: '0' }],
        'h6': ['18px', { lineHeight: '1.5', fontWeight: '600', letterSpacing: '0' }],
      },
      spacing: {
        '0': '0px',
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '8': '32px',
        '10': '40px',
        '12': '48px',
        '16': '64px',
        '20': '80px',
        '24': '96px',
        '32': '128px',
        '40': '160px',
        '48': '192px',
        '64': '256px',
      },
      boxShadow: {
        'sm': '0 1px 2px 0 rgba(0, 0, 0, 0.3)',
        'default': '0 1px 3px 0 rgba(0, 0, 0, 0.4), 0 1px 2px 0 rgba(0, 0, 0, 0.3)',
        'md': '0 4px 6px -1px rgba(0, 0, 0, 0.4), 0 2px 4px -1px rgba(0, 0, 0, 0.3)',
        'lg': '0 10px 15px -3px rgba(0, 0, 0, 0.5), 0 4px 6px -2px rgba(0, 0, 0, 0.3)',
        'xl': '0 20px 25px -5px rgba(0, 0, 0, 0.5), 0 10px 10px -5px rgba(0, 0, 0, 0.2)',
        'card': '0 2px 8px rgba(0, 0, 0, 0.3)',
      },
      borderRadius: {
        'sm': '4px',
        'md': '8px',
        'lg': '12px',
        'full': '100px',
        'pill': '100px',
      },
      maxWidth: {
        'content': '680px',
        'wide': '1280px',
        'xwide': '1400px',
      },
      lineHeight: {
        'tight': '1.0',
        'normal': '1.5',
        'relaxed': '1.75',
        'loose': '2.0',
        'heading': {
          '1': '1.0',
          '2': '1.1',
          '3': '1.2',
        },
      },
      letterSpacing: {
        'tight': '-0.025em',
        'normal': '0em',
        'wide': '0.025em',
        'heading': {
          '1': '-2.038px',
          '2': '-1.5px',
          '3': '-1px',
        },
      },
      screens: {
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1536px',
      },
      transitionDuration: {
        'default': '200ms',
        'fast': '150ms',
        'slow': '300ms',
      },
    },
  },
  plugins: [],
}
